### ISSUE TITLE
Tests Fail in GroovyFilesSpec of Chapter 2

### ISSUE THREAD

**Issue by adavis** [kkapelon/java-testing-with-spock#2]
If you run the tests from within the IntelliJ IDE the tests fail, but if you run them from the command line using: `mvn test` the tests pass.

<b>Stacktrace:</b>
java.io.FileNotFoundException: src/test/resources/quotes.txt (No such file or directory)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at groovy.util.CharsetToolkit.<init>(CharsetToolkit.java:69)
    at com.manning.spock.chapter2.GroovyFilesSpec.demo for reading a text file line by line(GroovyFilesSpec.groovy:20)

**Comment by kkapelon** [comment]
I cannot reproduce this with Java 7 and IntelliJ 13. The test finishes with no problems.
![test-passes](https://cloud.githubusercontent.com/assets/214914/6474837/f6f717e0-c20c-11e4-9bee-0de5eb923e81.png)

Will test tomorrow with Java 8 to see if this makes a difference.

**Comment by adavis** [comment]
I'm also using Java 7 with IntelliJ 13, maybe the way I imported the project is causing the issue?

![screen shot 2015-03-03 at 6 55 31 pm](https://cloud.githubusercontent.com/assets/141404/6475341/fee64ed4-c1d6-11e4-8450-33d4c3131084.png)

**Comment by eddumelendez** [comment]
I have tested running mvn test in Intellij 14 and everything is ok in java 7 & 8

**Comment by adavis** [comment]
I tested again by importing each chapter as a 'Project' instead of having them all together in one Project as a 'Module'.  Will close.

**Comment by kkapelon** [comment]
Ah! Good find. Ok I will write this in the readme of each chapter and also in the appendix of the book. Thank you.
